import React, { useState, useEffect } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const DeliveryManagement = () => {
  const [deliveredOrders, setDeliveredOrders] = useState([]);
  const [drivers, setDrivers] = useState([]);
  // Search query state for client-side filtering
  const [searchQuery, setSearchQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchDeliveredOrders();
    fetchDrivers();
  }, []);

  const fetchDeliveredOrders = async () => {
    try {
      setLoading(true);
      // Fetch orders with DELIVERED status
      const response = await axios.get('/api/orders?status=DELIVERED');
      console.log('DELIVERED orders response:', response.data);
      setDeliveredOrders(response.data.orders || []);
    } catch (err) {
      setError('Failed to fetch DELIVERED orders');
      console.error('Error fetching DELIVERED orders:', err);
    } finally {
      setLoading(false);
    }
  };

  const fetchDrivers = async () => {
    try {
      const response = await axios.get('/api/drivers');
      setDrivers(response.data.data || []);
    } catch (err) {
      console.error('Error fetching drivers:', err);
    }
  };

 const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-LK', {
    style: 'currency',
    currency: 'LKR'
  }).format(amount);
};


  const formatDate = (date) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'SHIPPED': return 'primary';
      case 'DELIVERED': return 'success';
      case 'CANCELLED': return 'error';
      default: return 'default';
    }
  };

  const downloadDeliveryPDF = () => {
    if (!deliveredOrders || deliveredOrders.length === 0) {
      alert('No delivered orders to download');
      return;
    }

    try {
      const doc = new jsPDF('p', 'pt', 'a4');
      const pageWidth = doc.internal.pageSize.width;
      const pageHeight = doc.internal.pageSize.height;

      // Header background
      doc.setFillColor(0, 90, 84);
      doc.rect(0, 0, pageWidth, 100, 'F');

      // Logo placeholder
      doc.setFillColor(255, 255, 255);
      doc.circle(60, 50, 25, 'F');
      doc.setFontSize(12);
      doc.setTextColor(0, 90, 84);
      doc.text('FF', 55, 55);

      // Title
      doc.setFontSize(28);
      doc.setTextColor(255, 255, 255);
      doc.text('FABRIC FLOW', 100, 45);
      doc.setFontSize(14);
      doc.setTextColor(220, 220, 220);
      doc.text('Management System', 100, 65);

      // Info box
      const now = new Date();
      const dateStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' });
      const timeStr = now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit' });

      doc.setFillColor(248, 249, 250);
      doc.roundedRect(40, 120, pageWidth - 80, 80, 5, 5, 'F');

      doc.setFontSize(20);
      doc.setTextColor(0, 90, 84);
      doc.text('DELIVERED ORDERS REPORT', 60, 150);

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Report Generated: ${dateStr} at ${timeStr}`, 60, 170);
      doc.text(`Generated By: System Administrator`, 60, 185);
      doc.text(`Total Records: ${deliveredOrders.length} orders`, 400, 170);
      doc.text(`Report ID: DLV-${Date.now().toString().slice(-6)}`, 400, 185);

      // Table data
      const tableData = deliveredOrders.map((order, idx) => [
        (idx + 1).toString(),
        order.orderId || (order._id ? `#${String(order._id).slice(-6)}` : 'N/A'),
        order.customer?.name || 'N/A',
        `${order.customer?.email || 'N/A'}${order.customer?.phone ? ' / ' + order.customer.phone : ''}`,
        formatCurrency(order.totalAmount ?? 0),
        formatDate(order.orderDate),
        `${order.paymentMethod || 'N/A'}${order.paymentStatus ? ' (' + order.paymentStatus + ')' : ''}`,
        order.orderStatus || 'DELIVERED'
      ]);

      autoTable(doc, {
        startY: 230,
        head: [[
          '#',
          'Order ID',
          'Customer',
          'Contact',
          'Amount',
          'Order Date',
          'Payment',
          'Status'
        ]],
        body: tableData,
        theme: 'striped',
        headStyles: {
          fillColor: [0, 90, 84],
          textColor: [255, 255, 255],
          fontSize: 10,
          fontStyle: 'bold',
          halign: 'center',
          cellPadding: 8
        },
        bodyStyles: {
          fontSize: 9,
          textColor: [60, 60, 60],
          cellPadding: 6,
          halign: 'left'
        },
        alternateRowStyles: { fillColor: [250, 250, 250] },
        columnStyles: {
          0: { cellWidth: 25, halign: 'center' },
          1: { cellWidth: 80 },
          2: { cellWidth: 110 },
          3: { cellWidth: 140 },
          4: { cellWidth: 70, halign: 'right' },
          5: { cellWidth: 85 },
          6: { cellWidth: 110 },
          7: { cellWidth: 60, halign: 'center' }
        },
        styles: {
          overflow: 'linebreak',
          lineWidth: 0.5,
          lineColor: [200, 200, 200],
          cellPadding: 6
        },
        margin: { left: 40, right: 40 },
        didDrawPage: function (data) {
          const footerY = pageHeight - 60;
          doc.setDrawColor(0, 90, 84);
          doc.setLineWidth(2);
          doc.line(40, footerY, pageWidth - 40, footerY);
          doc.setFontSize(8);
          doc.setTextColor(100, 100, 100);
          doc.text('Fabric Flow Management System | Confidential Document', 40, footerY + 20);
          doc.text(`Page ${data.pageNumber}`, pageWidth - 80, footerY + 20);
          doc.text(`Generated on ${dateStr}`, 40, footerY + 35);
          doc.text('© 2025 Fabric Flow. All rights reserved.', pageWidth - 180, footerY + 35);
        }
      });

      // Summary box
      const finalY = doc.lastAutoTable.finalY + 30;
      const totalValue = deliveredOrders.reduce((sum, o) => sum + (o.totalAmount || 0), 0);
      if (finalY < pageHeight - 120) {
        doc.setFillColor(0, 90, 84);
        doc.roundedRect(40, finalY, pageWidth - 80, 60, 5, 5, 'F');
        doc.setFontSize(12);
        doc.setTextColor(255, 255, 255);
        doc.text('REPORT SUMMARY', 60, finalY + 25);
        doc.setFontSize(10);
        doc.text(`Delivered Orders: ${deliveredOrders.length}`, 60, finalY + 45);
        doc.text(`Total Value: ${formatCurrency(totalValue)}`, 220, finalY + 45);
      }

      const fileName = `FabricFlow_Professional_Deliveries_Report_${dateStr.replace(/\//g, '-')}.pdf`;
      doc.save(fileName);
    } catch (err) {
      console.error('Error generating Delivery PDF:', err);
      alert('Failed to generate delivery report PDF');
    }
  };


  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-[400px]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-[#005A54]"></div>
      </div>
    );
  }

  // Prepare filtered list based on searchQuery (frontend-only)
  // Behavior: case-insensitive, 'starts with' matching against the
  // combined string "Order #<orderId> <customerName>" so searches like
  // 'O', 'Order', 'ORD...' or the raw order id 'ORD55418337639' (with or
  // without a leading '#') will match appropriately.
  const q = (searchQuery || '').trim().toLowerCase();
  const filteredOrders = q === '' ? deliveredOrders : deliveredOrders.filter((order) => {
    const orderId = (order.orderId || '').toString().toLowerCase();
    const orderIdWithHash = `#${orderId}`;
    const orderLabel = `order #${orderId}`; // lower-cased label
    const customerName = (order.customer?.name || '').toString().toLowerCase();

    // startsWith behavior per-field (keeps the UX of first-character filtering):
    // - If the user types 'order' or 'o' -> orderLabel startsWith(q) will match
    // - If the user types the raw id 'ord554...' -> orderId.startsWith(q) will match
    // - If the user types '#ord554...' -> orderIdWithHash.startsWith(q) will match
    // - If the user types a customer name starting letters -> customerName.startsWith(q) will match
    if (orderLabel.startsWith(q)) return true;
    if (orderIdWithHash.startsWith(q)) return true;
    if (orderId.startsWith(q)) return true;
    if (customerName.startsWith(q)) return true;

    return false;
  });

  return (
    <div className="p-4 md:p-16">
      <div className="flex justify-between items-center mb-12">
        <div>
          <h1 className="text-4xl font-bold text-[#005A54] mb-2">
            Delivery Management
          </h1>
          <p className="text-gray-600">
            View DELIVERED orders for review
          </p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={fetchDeliveredOrders}
            className="flex items-center px-4 py-2 bg-[#005A54] text-white rounded-lg hover:bg-[#004d47] transition-colors"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
            </svg>
            Refresh
          </button>
          <button
            onClick={downloadDeliveryPDF}
            className="flex items-center px-4 py-2 border border-[#005A54] text-[#005A54] rounded-lg hover:bg-[#f0fdfa] transition-colors"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v2a2 2 0 002 2h12a2 2 0 002-2v-2M7 10l5 5m0 0l5-5m-5 5V4" />
            </svg>
            Download PDF
          </button>
        </div>
      </div>

      {/* Search bar - real-time frontend filtering */}
      <div className="mb-6">
        <input
          type="text"
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          placeholder="Search orders by Order # or customer name (starts with)..."
          className="w-full md:w-1/2 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#005A54]"
        />
        {/*
          Behavior:
          - Filters deliveredOrders in real-time on each keystroke (frontend-only)
          - Case-insensitive
          - Uses 'starts with' matching: when user types the first character,
            only items whose name/order string starts with that character are shown.
          - Matches against a display string that includes 'Order #<orderId>' so
            inputs like 'O' or 'ORD' or the full "Order #ORD55418337639" will match.
        */}
      </div>

      {/* Statistics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6 mb-16">
        <div className="bg-blue-600 text-white rounded-lg p-6">
          <div className="flex items-center">
            <svg className="w-10 h-10 mr-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M20,8h-3V4H3C1.89,4 1,4.89 1,6v11h2c0,1.66 1.34,3 3,3s3-1.34 3-3h6c0,1.66 1.34,3 3,3s3-1.34 3-3h2v-5L20,8zM6,18.5c-0.83,0 -1.5,-0.67 -1.5,-1.5s0.67,-1.5 1.5,-1.5s1.5,0.67 1.5,1.5S6.83,18.5 6,18.5zM18,18.5c-0.83,0 -1.5,-0.67 -1.5,-1.5s0.67,-1.5 1.5,-1.5s1.5,0.67 1.5,1.5S18.83,18.5 18,18.5zM19,13H5V6h14V13z"/>
            </svg>
            <div>
              <h2 className="text-4xl font-bold">
                {deliveredOrders.length}
              </h2>
              <p className="text-sm">
                Delivered Orders
              </p>
            </div>
          </div>
        </div>
        <div className="bg-green-600 text-white rounded-lg p-6">
          <div className="flex items-center">
            <svg className="w-10 h-10 mr-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12,12c2.21,0 4,-1.79 4,-4s-1.79,-4 -4,-4s-4,1.79 -4,4S9.79,12 12,12zM21,9v3l-2,-1v4c0,1.1 -0.9,2 -2,2l-2,0v-2l2,0v-2.5l-1.5,0.75V9l3.5,-1.5V3l-2,0v-1h2C21.1,2 21,2.9 21,4v2l2,1v2H21zM9,13c-2.67,0 -8,1.34 -8,4v3h16v-3C17,14.34 11.67,13 9,13z"/>
            </svg>
            <div>
              <h2 className="text-4xl font-bold">
                {drivers.filter(d => d.status === 'active').length}
              </h2>
              <p className="text-sm">
                Active Drivers
              </p>
            </div>
          </div>
        </div>
        <div className="bg-amber-600 text-white rounded-lg p-6">
          <div className="flex items-center">
            <svg className="w-10 h-10 mr-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M19,3H5C3.9,3 3,3.9 3,5v14c0,1.1 0.9,2 2,2h14c1.1,0 2,-0.9 2,-2V5C21,3.9 20.1,3 19,3zM19,19H5V5h14V19zM17,12H7v-2h10V12zM15,16H7v-2h8V16zM17,8H7V6h10V8z"/>
            </svg>
            <div>
              <h2 className="text-4xl font-bold">
                {deliveredOrders.reduce((sum, order) => sum + order.totalAmount, 0).toLocaleString()}
              </h2>
              <p className="text-sm">
                Total Value (LKR)
              </p>
            </div>
          </div>
        </div>
        <div className="bg-cyan-600 text-white rounded-lg p-6">
          <div className="flex items-center">
            <svg className="w-10 h-10 mr-4" fill="currentColor" viewBox="0 0 24 24">
              <path d="M12,2C6.48,2 2,6.48 2,12s4.48,10 10,10s10,-4.48 10,-10S17.52,2 12,2zM10,17l-5,-5l1.41,-1.41L10,14.17l7.59,-7.59L19,8L10,17z"/>
            </svg>
            <div>
              <h2 className="text-4xl font-bold">
                {deliveredOrders.length > 0 ? Math.round((deliveredOrders.length / deliveredOrders.length) * 100) : 0}%
              </h2>
              <p className="text-sm">
                Completion Rate
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Orders Table */}
      <div className="bg-white rounded-lg shadow-lg overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <strong>Order Details</strong>
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <strong>Customer</strong>
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <strong>Amount</strong>
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <strong>Order Date</strong>
                </th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  <strong>Status</strong>
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredOrders.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-6 py-16 text-center">
                    <h3 className="text-xl font-semibold text-gray-500 mb-2">
                      No DELIVERED orders available
                    </h3>
                    <p className="text-gray-400">
                      Orders marked as "DELIVERED" will appear here
                    </p>
                  </td>
                </tr>
              ) : (
                filteredOrders.map((order) => (
                  <tr key={order._id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <p className="text-sm font-semibold text-gray-900">
                          Order #{order.orderId}
                        </p>
                        <p className="text-sm text-gray-500">
                          {order.items.length} item(s)
                        </p>
                        <p className="text-sm text-gray-500">
                          Payment: {order.paymentMethod} ({order.paymentStatus})
                        </p>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div>
                        <p className="text-sm font-semibold text-gray-900">
                          {order.customer.name}
                        </p>
                        <p className="text-sm text-gray-500">
                          {order.customer.email}
                        </p>
                        <p className="text-sm text-gray-500">
                          {order.customer.phone}
                        </p>
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <p className="text-sm font-semibold text-gray-900">
                        {formatCurrency(order.totalAmount)}
                      </p>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <p className="text-sm text-gray-900">
                        {formatDate(order.orderDate)}
                      </p>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`inline-flex px-2 py-1 text-xs font-semibold rounded-full ${
                        order.orderStatus === 'SHIPPED' ? 'bg-blue-100 text-blue-800' :
                        order.orderStatus === 'DELIVERED' ? 'bg-green-100 text-green-800' :
                        order.orderStatus === 'CANCELLED' ? 'bg-red-100 text-red-800' :
                        'bg-gray-100 text-gray-800'
                      }`}>
                        {order.orderStatus}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default DeliveryManagement;
