import React, { useState, useEffect } from "react";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function InventoryReports() {
  const [purchases, setPurchases] = useState([]);
  const [materials, setMaterials] = useState([]);
  const [suppliers, setSuppliers] = useState([]);
  const [reportLoaded, setReportLoaded] = useState(false);

  const now = new Date();
  const [selectedMonth, setSelectedMonth] = useState(
    `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`
  );

  useEffect(() => {
    if (!reportLoaded) {
      axios
        .get("https://fabricflow-backend1.onrender.com/api/Purchase")
        .then((res) => setPurchases(res.data.purchases || res.data))
        .catch((err) => console.error(err));

      axios
        .get("https://fabricflow-backend1.onrender.com/api/Supplier")
        .then((res) => setSuppliers(res.data.suppliers || res.data))
        .catch((err) => console.error(err));

      axios
        .get("https://fabricflow-backend1.onrender.com/api/Material")
        .then((res) => setMaterials(res.data.materials || res.data))
        .catch((err) => console.error(err));

      setReportLoaded(true);
    }
  }, [reportLoaded]);

  const [year, month] = selectedMonth.split("-");
  const firstDay = new Date(year, month - 1, 1);
  const lastDay = new Date(year, month, 0);

  const monthlyPurchases = purchases.filter((p) => {
    const date = new Date(p.date);
    return date >= firstDay && date <= lastDay;
  });

  const totalCost = monthlyPurchases.reduce(
    (sum, p) => sum + (p.totalCost || p.quantity * p.unitPrice),
    0
  );

  const handleDownloadPDF = () => {
    if (!monthlyPurchases.length) {
      alert("No purchases for this month!");
      return;
    }

    const doc = new jsPDF();

    // ===== HEADER WITH CIRCLE LOGO =====
    doc.setFillColor(0, 77, 64); // Dark green background
    doc.rect(0, 0, doc.internal.pageSize.width, 30, "F");

    // White circle logo
    doc.setFillColor(255, 255, 255);
    doc.circle(15, 15, 8, "F"); // x=15, y=15, radius=8
    doc.setTextColor(0, 77, 64);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("FF", 15, 18, { align: "center" });

    // Main Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("FABRIC FLOW", 32, 15); // Move right to leave space for circle

    // Subtitle
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Management System", 32, 22);

    // ===== WHITE TITLE BOX =====
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(10, 40, doc.internal.pageSize.width - 20, 20, 3, 3, "F");
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 77, 64);
    doc.text("MONTHLY INVENTORY REPORT", doc.internal.pageSize.getWidth() / 2, 53, {
      align: "center",
    });

    // ===== REPORT META INFO =====
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(33, 33, 33);
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, 14, 70);
    doc.text(`Generated By: System Administrator`, 14, 76);
    doc.text(`Month: ${selectedMonth}`, 14, 82);
    doc.text(
      `Total Records: ${monthlyPurchases.length}`,
      doc.internal.pageSize.getWidth() - 80,
      70
    );
    doc.text(
      `Report ID: INV-${Math.floor(Math.random() * 900000) + 100000}`,
      doc.internal.pageSize.getWidth() - 80,
      76
    );

    // ===== TABLE =====
    const tableData = monthlyPurchases.map((p) => {
      const supplierName =
        suppliers.find((s) => s._id === p.supplierId)?.name ||
        p.supplierId?.name ||
        "N/A";
      const materialName =
        materials.find((m) => m._id === p.materialId)?.name ||
        p.materialId?.name ||
        "N/A";
      const total = p.totalCost || p.quantity * p.unitPrice;

      return [
        p.purchaseId,
        supplierName,
        materialName,
        p.quantity,
        p.unitPrice.toFixed(2),
        total.toFixed(2),
        new Date(p.date).toLocaleDateString(),
      ];
    });

    autoTable(doc, {
      head: [["ID", "Supplier", "Material", "Qty", "Unit Price", "Total Cost", "Date"]],
      body: tableData,
      startY: 90,
      theme: "grid",
      styles: {
        fontSize: 10,
        cellPadding: 3,
        halign: "center",
        valign: "middle",
        lineColor: [200, 200, 200],
      },
      headStyles: {
        fillColor: [0, 77, 64],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        halign: "center",
      },
      alternateRowStyles: {
        fillColor: [245, 245, 245],
      },
    });

    // ===== SUMMARY SECTION =====
    const summaryY = doc.lastAutoTable.finalY + 10;
    doc.setFillColor(0, 77, 64);
    doc.roundedRect(10, summaryY, doc.internal.pageSize.width - 20, 20, 3, 3, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(
      `Total Cost: Rs. ${totalCost.toFixed(2)}`,
      doc.internal.pageSize.getWidth() / 2,
      summaryY + 13,
      { align: "center" }
    );

    // ===== FOOTER =====
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(120, 120, 120);
    doc.text(
      "Fabric Flow Management System | Confidential Document",
      doc.internal.pageSize.getWidth() / 2,
      pageHeight - 10,
      { align: "center" }
    );

    doc.save(`Monthly_Report_${selectedMonth}.pdf`);
  };

  return (
    <div className="flex min-h-screen">
    
      <div className="flex-1 overflow-y-auto font-sans">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-green-900">
            Monthly Inventory Report
          </h1>
          <div className="flex gap-2">
            <input
              type="month"
              value={selectedMonth}
              max={`${now.getFullYear()}-${String(
                now.getMonth() + 1
              ).padStart(2, "0")}`}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="p-2 rounded-lg border border-green-300 shadow-inner text-green-900"
            />
            <button
              onClick={handleDownloadPDF}
              className="bg-green-900 text-white px-4 py-2 rounded-lg font-semibold hover:bg-green-950 transition"
            >
              Download PDF
            </button>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow overflow-x-auto">
          <table className="min-w-full border-separate border-spacing-y-2">
            <thead>
              <tr>
                {[
                  "ID",
                  "Supplier",
                  "Material",
                  "Quantity",
                  "Unit Price (Rs.)",
                  "Total Cost (Rs.)",
                  "Date",
                ].map((header) => (
                  <th
                    key={header}
                    className="text-left px-4 py-2 bg-green-50 text-green-900 font-semibold border-b-2"
                  >
                    {header}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {monthlyPurchases.map((p) => {
                const supplierName =
                  suppliers.find((s) => s._id === p.supplierId)?.name ||
                  p.supplierId?.name ||
                  "N/A";
                const materialName =
                  materials.find((m) => m._id === p.materialId)?.name ||
                  p.materialId?.name ||
                  "N/A";
                const total = p.totalCost || p.quantity * p.unitPrice;

                return (
                  <tr key={p._id} className="transition hover:bg-green-100">
                    <td className="px-4 py-2">{p.purchaseId}</td>
                    <td className="px-4 py-2">{supplierName}</td>
                    <td className="px-4 py-2">{materialName}</td>
                    <td className="px-4 py-2">{p.quantity}</td>
                    <td className="px-4 py-2">{p.unitPrice.toFixed(2)}</td>
                    <td className="px-4 py-2">{total.toFixed(2)}</td>
                    <td className="px-4 py-2">
                      {new Date(p.date).toLocaleDateString()}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <div className="mt-3 font-bold text-right text-green-900">
          Total Cost: Rs. {totalCost.toFixed(2)}
        </div>
      </div>
    </div>
  );
}

export default InventoryReports;
